<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>FightingAllstar.Core</AssemblyName>
    <RootNamespace>FightingAllstar.Core</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DebugType>none</DebugType>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <OutputPath>../../Assets/Project/Plugins/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FightingAllstar.Contracts/FightingAllstar.Contracts.csproj" />
  </ItemGroup>
</Project>
